[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    # X-Frame-Options can be used to indicate whether or not a browser should be
    # allowed to render a page in a <frame>, <iframe>, <embed> or <object>.
    # Sites can use this to avoid click-jacking attacks
    X-Frame-Options = "DENY"

    # The HTTP X-XSS-Protection response header is a feature of Internet
    # Explorer, Chrome and Safari that stops pages from loading when they detect
    # reflected cross-site scripting (XSS) attacks. Although these protections
    # are largely unnecessary in modern browsers when sites implement a strong
    # Content-Security-Policy that disables the use of inline JavaScript
    # ('unsafe-inline'), they can still provide protections for users of older
    # web browsers that don't yet support CSP.
    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
    X-XSS-Protection = "1; mode=block"
